### PR TITLE
switch v1 readthedocs build from conda to mamba

### PR DESCRIPTION
**Pull request by kevingreenman**
## Description
This PR changes the v1 Read the Docs (RTD) yml file to use mamba instead of conda to build the documentation. In preparation for the v2 release (which will have a new set of RTD documentation) I would like to have the v1 RTD working again so that the note I added to our RTD homepage in [this commit](https://github.com/chemprop/chemprop/commit/386d480553e493577b050d7c47f51aba3e0ac6dc) will show up if someone is still using v1.x and tries to look at the old documentation. We regularly get people asking questions in issues/discussions because they haven't looked at the README and assume that our RTD is up-to-date for v1.x (which is not an unreasonable assumption, IMO).

## Example / Current workflow
Our v1 documentation has been failing to build since October 2022, sometimes due to excessive memory consumption (e.g. see [here](https://readthedocs.org/projects/chemprop/builds/18376019/)). 

Our build sometimes also fails with the error `virtualenv: error: the following arguments are required: dest` when running `python -mvirtualenv $READTHEDOCS_VIRTUALENV_PATH` (e.g. see [here](https://readthedocs.org/projects/chemprop/builds/23445565/)). This is related to this RTD [issue](https://github.com/readthedocs/readthedocs.org/issues/10907).

## Bugfix / Desired workflow
Based on the RTD documentation [here](https://docs.readthedocs.io/en/stable/guides/conda.html#making-builds-faster-with-mamba) and [here](https://docs.readthedocs.io/en/stable/config-file/v2.html#conda), I believe this is the best way to speed up the build and reduce memory requirements. I think this may solve both errors encountered above. If this doesn't work, some other fixes are described [here](https://docs.readthedocs.io/en/stable/guides/build-using-too-many-resources.html). 

## Questions
The build sometimes also fails for no apparent reason and with no error message after running `git clean -d -f -f`, which appears to execute successfully (e.g. see [here](https://readthedocs.org/projects/chemprop/builds/23327660/)). It's unclear to me whether this PR can fix this issue since it's not clear what the issue is in the first place.

### CODE REVIEW

**Review by davidegraff — APPROVED** [review]
For v2, is it possible to switch our entire environment to python? I.e., switch to:
```yaml
build:
  tools:
    python: "3.11"
[...]
python:
  install:
    - requirements: docs/requirements.txt
```
It seems like all of our requirements are now `pip`-installable, so we shouldn't even neeed to rely on `conda`/`mamba`

**Comment by kevingreenman** [comment]
> For v2, is it possible to switch our entire environment to python? I.e., switch to:
> 
> ```yaml
> build:
>   tools:
>     python: "3.11"
> [...]
> python:
>   install:
>     - requirements: docs/requirements.txt
> ```
> 
> It seems like all of our requirements are now `pip`-installable, so we shouldn't even neeed to rely on `conda`/`mamba`

Yes, I think so. Though I'm not sure if it's correct to do it the way you have it above or like you did in [this commit](https://github.com/chemprop/chemprop/commit/e370cddc379f8b36a25c670abd9ff2f034866b88).

**Comment by davidegraff** [comment]
I _think_ they're equivalent, and probably what I had already implemented is simpler.

**Comment by kevingreenman** [comment]
RTD build succeeded! Merging now.

**Comment by kevingreenman** [comment]
Also, for v2, not clear how we'll deal with the current installation issues in #580 for the docs

**Pull request merged**
