### PR TITLE
V2/fix and improve pyproject toml

### PR DESCRIPTION
**Pull request by c-w-feldmann**
### Mypy
The pyproject.toml did not include the py.typed file (which enables support for [mypy](https://mypy.readthedocs.io/en/stable/installed_packages.html#using-installed-packages-with-mypy-pep-561))
### Package detection
```yaml
[tool.setuptools]
packages = ["chemprop"]
```
would only install .py files located in `chemprop` ignoring all sub-folders.  
Automatic recognition of these folders was achieved by replacing these lines with:
```yaml
Changing [tool.setuptools.packages.find]
exclude = ["tests", "examples", "docs"]
```

### CODE REVIEW

**Comment by davidegraff** [comment]
thanks for the fix! re: `[tool.setuptools.packages.find]` configuration, the `setuptools` docs seem to imply that both `docs` and `test` [are automatically filtered](https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#flat-layout). Is it possible to exclude these from the list?

**Comment by c-w-feldmann** [comment]
> [Is it possible to delete this option altogether?](https://github.com/chemprop/chemprop/pull/732#issuecomment-1998027874)

I tested it and it seems to work. Corresponding rows were removed

**Comment by davidegraff** [comment]
And you can confirm that the source distribution contains only the relevant files?

**Review by davidegraff — APPROVED** [review]

**Review by JacksonBurns — CHANGES_REQUESTED** [review]
I am confused - the `2.0.0rc1` includes the entire contents of the git repo (check for yourself with the source distribution from PyPI [here](https://files.pythonhosted.org/packages/ea/27/0d79115b87fb68adb8b39f1c15245fa97716bb4e2ff72a47925b017563c7/chemprop-2.0.0rc1.tar.gz)). The subpackages  in `chemprop` _are_ found, as well as the stuff we shouldn't include like `docs` etc. as mentioned above, which I am glad this PR has removed.

As far as `mypy` goes it seems like a useful tool, but if we don't directly integrate into our Continuous Integration I am against carrying around the `py.typed` in the repo. If it's helpful for local development, devs can add it to their copy, but unless we actually enforce using it across the whole repo with CI then it just seems like clutter.

**Comment by c-w-feldmann** [comment]
@JacksonBurns 
The py.typed is not for internal checking with mypy, but for the generation of stubs so projects importing chemprop can verify that chemprop classes and functions are called with the correct types.

**Comment by JacksonBurns** [comment]
Is there then a way to enforce proper type notations in the CI so we can verify going forward that we actually do support mypy? Is this covered by flake8 or black, which we have previously used?
________________________________

**Comment by c-w-feldmann** [comment]
> Is this [mypy] covered by flake8 or black, which we have previously used?
No it is not. To have the installation fixed, I removed the mypy related stuff and will create a ticket for the stub generation.

**Review by JacksonBurns — APPROVED** [review]
Thank you for breaking these up - this LGTM and I will follow up on the new ticket.

**Pull request merged**
