### PR TITLE
Create test folder for v2

### PR DESCRIPTION
**Pull request by am2145**
This commit creates a test folder in v2 for v2/tests and copied the relevant tests from the outside test folder to v2/tests. Import statements have been updated to make sure the tests run but further testing is required to make sure the tests function as intended. A future pull request is needed to clean up/remove the v2 tests from the outside folder.

### CODE REVIEW

**Review by oscarwumit — APPROVED** [review]
Thanks for the PR. All looks good.

**Comment by davidegraff** [comment]
why are the tests located under the source-code directory rather than outside it? Do we want to distribute the unit tests with the package itself?

**Comment by am2145** [comment]
That's a good question. The tests directory is currently located in v2 just to distinguish it from the v1 tests in the outside directory whilst we work on adding new unit tests. We can definitely change where it (and the v1 tests) end up in the final distribution. What would you recommend?

**Comment by davidegraff** [comment]
I think they should be in a separate top-level directory. Otherwise they'll get pulled into the wheel during packaging unnecessarily.

**Pull request merged**
