### PR TITLE
Add simple cache to CLI

### LINKED ISSUE #792: [FEATURE]: Cache in CLI
#697 added caching to v2. We haven't made it available through the CLI yet

### PR DESCRIPTION
**Pull request by KnathanM**
We want to have caching in the CLI as it speeds up training. I decided to always have caching on as the default with the option to turn it off. This is because in my tests with 1 M datapoints, the cached Molgraphs only took on the order of 10 GB of memory. I figure if someone is trying to train on 1M datapoints, they probably have that much memory to spare. 

I don't cache the test set as it is only used once so the MolGraphs only need to be calculated once and caching doesn't help with that. 

My tests:
```
from rdkit import Chem
from chemprop import data

mol = Chem.MolFromSmiles("CC1(C(N2C(S1)C(C2=O)NC(=O)CC3=CC=CC=C3)C(=O)O)C") # Penicillin
datapoints = [data.MoleculeDatapoint(mol) for _ in range(1_000_000)]
dataset = data.MoleculeDataset(datapoints)
dataset.cache = True
```

I found making 1M datapoints took about half a gig. Then caching added about 10 gigabytes. I also estimated the size of a single MolGraph:
```
from sys import getsizeof
from chemprop import featurizers
feat = featurizers.SimpleMoleculeMolGraphFeaturizer()
mg = feat(mol)
(getsizeof(mg.V)
+ getsizeof(mg.E)
+ getsizeof(mg.edge_index)
+ getsizeof(mg.rev_edge_index)
+ getsizeof(mg))
```

This gives 13992 bytes. So 1M penicillin MolGraphs would be about 14 GB which is in the same order of magnitude.

As I side note, I found that after setting the cache `dataset.cache = True`, trying to clear the cache `dataset.cache = False` only reduced the memory by 1G instead of 10G, so we may not be clearing the cache correctly. This can be looked into later. 

Closes #792

### CODE REVIEW

**Comment by JacksonBurns** [comment]
@KnathanM just a heads up that `getsizeof` is not guaranteed to be correct for anything other than the standard library, as per the [python docs](https://docs.python.org/3/library/sys.html#sys.getsizeof) - it _might be_, but could you double check your numbers with something like `time -v chemprop ...`?

**Comment by davidegraff** [comment]
@JacksonBurns `getsizeof()` is fine to use on numpy arrays as long as you're not storing additional attributes in the array [[1](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.nbytes.html)]. @KnathanM 's calculation is correct for the size of a `MolGraph`.

**Comment by davidegraff** [comment]
@KnathanM you'll want to use a snippet like this:
```python
import sys
from rdkit import Chem
from chemprop import featurizers

mol = Chem.MolFromSmiles("CC1(C(N2C(S1)C(C2=O)NC(=O)CC3=CC=CC=C3)C(=O)O)C") # Penicillin
feat = featurizers.SimpleMoleculeMolGraphFeaturizer()

mg = feat(mol)
nbytes = sum(x.nbytes for x in mg) + sys.getsizeof(mg)
print(f"{nbytes/1000**2:0.2f} MB")
```

**Comment by shihchengli** [comment]
For the side note, is it possible the memory for [`self._mgs`](https://github.com/chemprop/chemprop/blob/main/chemprop/featurizers/molgraph/cache.py#L58) is not cleaned after using `MolGraphCacheOnTheFly` as the new `self.mg_cache` object?

**Comment by davidegraff** [comment]
@shihchengli it depends on whether the garbage collector has been called. When `cache = False` is called, the previous `MolGraphCache` has its refcount decremented to 0 and is thus marked for garbage collection. But until that event happens, the object and all of its underlying `MolGraph`s still exist on the heap. It's tempting to manually clear them, but that gets into the territory of manual memory management, which is generally unadvisable with a garbage-collected language like python.

**Comment by shihchengli** [comment]
Thanks for the information! I think the garbage collector will be called automatically during the process, so it probably won't bother us. Moreover, the issue Nathan mentioned only occurs when caching those MolGraphs first and setting `dataset.cache=False` afterwards. This doesn't seem like a usual operation during model training.

**Comment by KnathanM** [comment]
@JacksonBurns Here are the results from `time` (using a dataset of 100k molecules). I'm not sure how to interpret the results though

```
Command being timed: "chemprop train --no-cache --data-path qm9_100k.csv"
User time (seconds): 19.64
System time (seconds): 4.90
Percent of CPU this job got: 73%
Elapsed (wall clock) time (h:mm:ss or m:ss): 0:33.33
Average shared text size (kbytes): 0
Average unshared data size (kbytes): 0
Average stack size (kbytes): 0
Average total size (kbytes): 0
Maximum resident set size (kbytes): 1369932
Average resident set size (kbytes): 0
Major (requiring I/O) page faults: 17043
Minor (reclaiming a frame) page faults: 1028997
Voluntary context switches: 59796
Involuntary context switches: 1463
Swaps: 0
File system inputs: 1014064
File system outputs: 1032
Socket messages sent: 0
Socket messages received: 0
Signals delivered: 0
Page size (bytes): 4096
Exit status: 0


Command being timed: "chemprop train --data-path qm9_100k.csv"
User time (seconds): 61.43
System time (seconds): 4.64
Percent of CPU this job got: 95%
Elapsed (wall clock) time (h:mm:ss or m:ss): 1:09.04
Average shared text size (kbytes): 0
Average unshared data size (kbytes): 0
Average stack size (kbytes): 0
Average total size (kbytes): 0
Maximum resident set size (kbytes): 1728796
Average resident set size (kbytes): 0
Major (requiring I/O) page faults: 1521
Minor (reclaiming a frame) page faults: 1748999
Voluntary context switches: 13464
Involuntary context switches: 519
Swaps: 0
File system inputs: 130808
File system outputs: 112
Socket messages sent: 0
Socket messages received: 0
Signals delivered: 0
Page size (bytes): 4096
Exit status: 0
```

**Comment by JacksonBurns** [comment]
@KnathanM thanks for running! The `Maximum resident set size (kbytes):` is the peak RAM used during execution. Looks like no caching using ~1.4 GB whereas caching used ~1.7 GB. Pretty close to your initial estimate!

Interesting that the wall time was more than doubled _with caching_ - was this not running for a reasonable amount of epochs, meaning that we wouldn't see the benefit of spending execution time caching instead of training? Or something else?

**Comment by KnathanM** [comment]
> @KnathanM thanks for running! The `Maximum resident set size (kbytes):` is the peak RAM used during execution. Looks like no caching using ~1.4 GB whereas caching used ~1.7 GB. Pretty close to your initial estimate!
> 
> Interesting that the wall time was more than doubled _with caching_ - was this not running for a reasonable amount of epochs, meaning that we wouldn't see the benefit of spending execution time caching instead of training? Or something else?

And thank you for helping interpret it. This ran for 0 epochs, I forgot to mention originally I included `return` in `main` of `train.py` before `train_model` so that it went through all the steps to get ready to train but didn't. My hope was that this would give a fair estimate of the memory difference of the chemprop set up with and without caching. So for the caching case, it had to featurize all the molecules, while for no caching it featurized none of them (and would have done so on the fly during training). 

Looks like featurizing is already pretty fast, only ~30 seconds, so caching may only marginally save time, especially with parallel dataloading, which caching does not yet support. But the benchmarks will show what the timing vs. memory tradeoff really is.

**Review by davidegraff — APPROVED** [review]
For benchmarking purposes, we'll want to use some metric of $\text{s} \cdot \text{batch}$ and look at this metric along the axes of both batch size and number of parallel workers.

**Review by shihchengli — APPROVED** [review]

**Pull request merged**
