### PR TITLE
adding chemistry informed functionality

### PR DESCRIPTION
**Pull request by JurgisR**
## Description

Adding a chemistry informed functionality (a paper coming soon, no preprint yet), but details can be read on the previous repo - https://github.com/learningmatter-mit/Chem-prop-pred
Chemistry informed part works by predicting Arrhenius based parameters for ionic conductivity of polymers.

## Example / Current workflow
Include a sample workflow to either **(a)** reproduce the bug with current codebase or **(b)** showcase the deficiency does this PR seeks to address

## Bugfix / Desired workflow
Include either **(a)** the same workflow from above with the correct output produced via this PR **(b)** some (pseudo)code containing the new workflow that this PR will (seek to) implement

## Questions
If there are open questions about implementation strategy or scope of the PR, include them here

## Relevant issues
If appropriate, please tag them here and include a quick summary

## Checklist
- [ ] linted with flake8?
- [x ] (if appropriate) unit tests added?

### CODE REVIEW

**Comment by davidegraff** [comment]
I'm generally loathe to add yet *another* functionality to this repository. The core mission of `chemprop` should be as a package implementing message-passing neural networks for molecular property prediction. Clearly, this idea is extensible to other forms of prediction as well, like this PR shows. But I don't think adding this functionality furthers the primary goal. Rather, it adds another piece of code that will have to be maintained by the development team, a task that's challenging given that no one on the dev team deals with this application area.

**Comment by kevingreenman** [comment]
@davidegraff I agree that we should be cautious about adding new features like this if we won't be able to maintain them, but in this case I think we can consider adding it. @JurgisR is in Rafa's group, and he made the PR based on my advice. Although I don't work on ionic conductivity of polymers, I'm working on similar things in physics-based priors and will be happy to make sure this part gets maintained (at least for the next couple years). I think since Arrhenius relationships show up everywhere, this could be widely applicable and maybe of interest to some MLPDS people as well.

**Comment by kevingreenman** [comment]
@JurgisR check the format of the arguments you're passing to the integration test you added, it looks like it's throwing an error. And you can check if your tests are passing on your local branch by running `pytest` from the `tests/` directory

**Comment by cjmcgill** [comment]
This reads to me as very specific to this application. Good structure but I don't know how much it can apply for other properties.

**Comment by cjmcgill** [comment]
This reads to me as being a little too application-specific. It's a good structure but I don't know how it gets applied more widely. I would opt not to add it.

If it's something we really want to do, then I would look around and see if there's a way to make this self-contained as a built class that slots into the model in as few places as possible and keeps the tricky logic and transforms internal to the class.

**Comment by JurgisR** [comment]
Thanks for all the comments. After chatting some more with Kevin we decided that it would indeed clutter more chemprop, so I decided to just close the PR.

**Pull request closed without merging**
