### PR TITLE
Improve Colab example notebook

### PR DESCRIPTION
**Pull request by kevingreenman**
## Description
Add more examples and faster setup to Colab example notebook

## Current workflow
The "Setup" cell of the current colab notebook would take minutes to run to install miniconda and rdkit.  The original notebook only contained a few examples.

## Desired workflow
This improved installation process takes ~40 seconds, and the new notebook shows a wider range of Chemprop functionality.

### CODE REVIEW

**Review by cjmcgill — APPROVED** [review]
Improvements to the colab notebook look good.

Good as is. Something that you could add if you wanted to. This notebook seems relevant for the tutorial and resource section. You could add it to one of the lines there or add a new line for it.

**Comment by davidegraff** [comment]
will defer to @cjmcgill here

**Comment by cjmcgill** [comment]
I'm actually having it fail on setup when I run it now. I thought it had gone through but I guess I jumped the gun.

**Comment by cjmcgill** [comment]
`ERROR: Could not find a version that satisfies the requirement lazy-loader==0.1rc2 (from pandas-flavor>=0.2.0->chemprop==1.4.1) (from versions: none)
ERROR: No matching distribution found for lazy-loader==0.1rc2 (from pandas-flavor>=0.2.0->chemprop==1.4.1)`

**Review by cjmcgill — APPROVED** [review]
Okay, now that I'm using the right notebook, it looks great. It runs, and I merged it onto the master to make sure, and it runs then too. Loads up much faster and great to have all those extra examples.

**Pull request merged**
