### PR TITLE
V2/fix examples

### LINKED ISSUE #559: [TODO]: fix example script and notebooks
**Notes**
Recent changes have broken `example.py` and the notebooks in `examples/` (these are not included in our testing for PRs). 

Is there a way to test these all automatically as part of our testing for each new PR (e.g. just make sure they run to completion without errors)?

### PR DESCRIPTION
**Pull request by kevingreenman**
## Description
Fixes #559 

Fixed so far:
- [x] `example.py`
- [x] `examples/training.ipynb`
- [x] `examples/predicting.ipynb`
- [x] `examples/convert_v1_to_v2.ipynb`

### CODE REVIEW

**Comment by kevingreenman** [comment]
@hwpang since you're the original author of these notebooks, could you help figure out why `load_from_checkpoint` is giving an error?

@davidegraff @am2145 is this related to the issue you guys had discussed previously about how to save checkpoint files?

This is the stack trace:
```
KeyError                                  Traceback (most recent call last)
[~/code/chemprop/examples/predicting.ipynb] Cell 6 line 1
----> [1] mpnn = models.MPNN.load_from_checkpoint(checkpoint_path)
      [2] mpnn

File [~/code/chemprop/chemprop/models/model.py:226], in MPNN.load_from_checkpoint(cls, checkpoint_path, map_location, hparams_file, strict, **kwargs)
    [222] @classmethod
    [223] def load_from_checkpoint(
    [224]     cls, checkpoint_path, map_location=None, hparams_file=None, strict=True, **kwargs
    [225] ) -> MPNN:
--> [226]     hparams = torch.load(checkpoint_path)["hyper_parameters"]
    [228]     kwargs |= {
    [229]         key: hparams[key].pop("cls")(**hparams[key])
    [230]         for key in ("message_passing", "agg", "predictor")
    [231]     }
    [233]     return super().load_from_checkpoint(
    [234]         checkpoint_path, map_location, hparams_file, strict, **kwargs
    [235]     )

KeyError: 'hyper_parameters'
```

I tried to fix this based on what we have in the train/predict CLI, but it appears that recent changes have broken those as well.

**Comment by hwpang** [comment]
@kevingreenman Thanks for tagging me! Yes, I will look into this.

**Comment by kevingreenman** [comment]
@hwpang this is perfect, thank you! I added the checkpoint file that was output from the modified training notebook to the `tests/data/` folder so that the prediction notebook will run out of the box without having to input the actual name of the checkpoint, or someone can run the prediction notebook without first running the training notebook. I think this will be helpful for if we run the notebooks automatically as in #562.

**Comment by hwpang** [comment]
@kevingreenman Yeah, I think it makes sense to have it saved in the `tests/data/`! I can rebase https://github.com/chemprop/chemprop/pull/562 with your PR.

**Review by hwpang — APPROVED** [review]
Thanks for fixing the notebooks! LGTM!

**Pull request merged**
