### PR TITLE
Fix bug when checking if features or descriptors are None type.

### PR DESCRIPTION
**Pull request by am2145**
## Description
This PR modifies `datasets.py` to fix some small bugs when checking if features and descriptors are `NoneType`  in the 'normalize_inputs()' function.

### CODE REVIEW

**Review by hwpang — APPROVED** [review]
LGTM

**Comment by davidegraff** [comment]
is there a test for this bug? I believe you that it's there, but our tests have been passing, but they're missing coverage if there's a bug you needed to manually catch.

**Comment by hwpang** [comment]
@davidegraff Good call, I don't think we have currently. But we should add tests for features. I will make an issue for this.

**Comment by am2145** [comment]
> is there a test for this bug? I believe you that it's there, but our tests have been passing so they're missing coverage if there's a bug you needed to manually catch.

Good question. It has been a while, but I remember @xiaoruiDong and I encountering the bug during some initial testing when passing additional atom and bond features and descriptors. @hwpang has opened the issue and we'll make sure to have a dedicated test for additional features and descriptors when it's implemented.

**Pull request merged**
