### PR TITLE
Adding Unit Testing and Some Changes to Integration Testing

### PR DESCRIPTION
**Pull request by cjmcgill**
PR in progress. 

This PR is mostly for the purpose of adding a file with unit testing to Chemprop.

Additionally, some changes to the integration testing. Made the margin for testing tighter (5% to 1.5%) and reduced the number of epochs used in training.

### CODE REVIEW

**Comment by mliu49** [comment]
This is a great start! I have a couple suggestions:
- If you switch to saving the test files, then the TemporaryDirectory context manager could possibly be removed
- It might be worth going ahead and making the unit tests into a directory, with a file for each test class
- Each of the individual tests and assertions in `test_get_task_names` should ideally be put in separate test methods; otherwise the test will stop on the first failed assertion

**Comment by cjmcgill** [comment]
@mliu49 

- Would we want to save the test files? Doing it all in a temporary space seemed like a clean way to do it.
- Yes, even just three functions in, this is clearly going to be too big for one file. I'll switch over to a directory.
- With unit tests in a directory, it makes the formatting for this much nicer. Then each function to test can be a class and each assertion can be its own test function.

**Comment by mliu49** [comment]
I think writing to a temp directory is best if you don't need the files. I guess I was confused by the changes to manually set the `save_dir` and assumed you wanted to keep the files for some reason.

**Comment by cjmcgill** [comment]
I had a questionable reason for that and you probably have a better suggestion. I wanted a way to easily tell which of the parameterized conditions failed during testing. The tests had a subscript that indicated which parameter set. But each parameter also had this `name` field that was unused so I put it into the save_dir so that it would be easily visible in the test output from the "save results to <save_dir>" line. But it might just be better to rely on the subscripts alone.

**Comment by mliu49** [comment]
I'm not sure what you mean by subscript? It seems like pytest appends the `name` value to the name of the test, which should be displayed when tests fail. (As an aside, maybe it would be helpful to include the `-v` arg to pytest in github actions?)

If you want to include the name in `save_dir`, you could append it to the path created by TemporaryDirectory. Right now I think you're overwriting the `save_dir` variable so it doesn't actually use the TemporaryDirectory.

**Comment by cjmcgill** [comment]
@mliu49 by subscript I meant the integer in the test name just before the "name" value is included. And I had somehow missed that the name value was there, right in front of my face. Renaming the save_dir is unnecessary and I'll take it out.

I like the -v option, especially with there being so many tests in the integration tests that take a little while.

**Comment by cjmcgill** [comment]
Looks like pytest -v is not a valid option for github actions?

**Comment by davidegraff** [comment]
I think it is? I have no issue with using `pytest -v` in my [other CI](https://github.com/coleygroup/pyscreener/blob/main/.github/workflows/CI.yaml)

**Comment by cjmcgill** [comment]
@davidegraff Either it's a GitHub actions specific limitation or I flubbed the syntax somewhere. I'll take another try at it.

**Comment by cjmcgill** [comment]
Truncating unit testing efforts in this PR. This PR will only include unit testing for the data/utils.py functions. But adding one as an example is needed to add more unit test files in future PRs.

**Comment by davidegraff** [comment]
pretty much looks good to me with one suggestion: adding in coverage for the `ValueError` introduced in #257. Otherwise looks great!

**Review by davidegraff — APPROVED** [review]

**Comment by cjmcgill** [comment]
> pretty much looks good to me with one suggestion: adding in coverage for the `ValueError` introduced in #257. Otherwise looks great!

Good suggestion. Have added tests for that error.

**Pull request merged**
