### PR TITLE
V2: run example notebooks in GitHub Actions

### PR DESCRIPTION
**Pull request by hwpang**
## Description
Addressed questions regarding testing example notebooks raised in https://github.com/chemprop/chemprop/issues/559. Building on top of and should be merged after https://github.com/chemprop/chemprop/pull/560. Attempting to run example notebooks using pytest plugin https://github.com/treebeardtech/nbmake in GitHub Action.

## Checklist
- [ ] linted with flake8?
- [ ] (if appropriate) unit tests added?

### CODE REVIEW

**Comment by kevingreenman** [comment]
@hwpang thanks for the PR, this looks like a great feature to add to our testing, especially if we plan to include the notebooks directly in our documentation as mentioned in #556 

If you agree with my last change in #560, could you update this PR to include that change as well?

**Comment by kevingreenman** [comment]
One other thing I am wondering about relevant to this: should we include `ipykernel` as part of our dependencies (or maybe in a new set of optional dependencies called `notebooks`) in `pyproject.toml` so that one can run the example notebooks in VS Code after installing the chemprop environment, without having to take an additional step?

**Comment by kevingreenman** [comment]
Also, should we remove `example.py` so our only examples are notebooks in the `examples/` folder?

**Comment by hwpang** [comment]
Thanks for the comments! Yeah, I think it makes sense to include a new set of optional dependencies for people who are interested in using the notebooks. I don't have a strong opinion on whether to keep or remove `example.py`. I can add it to the unit test if we decide to keep it. We should also update the code to use `pandas` for parsing data instead of `csv` like we did in https://github.com/chemprop/chemprop/pull/514.

**Comment by hwpang** [comment]
I rebased with the newest `v2/dev`!

**Comment by hwpang** [comment]
@kevingreenman I think this PR is ready as it is, and we can discuss whether to remove `example.py` in the next dev 2 meeting. What do you think?

**Review by kevingreenman — APPROVED** [review]

**Pull request merged**
