### PR TITLE
Fix bug for tanimoto distance measure

### PR DESCRIPTION
**Pull request by fhvermei**
Simple bug fix for tanimoto measure introduced after changes for multiple molecules. 
The other distance measures are not affected (I ran some tests).
Note that this function does not work for multiple molecules or for extra features (mol, atom and bond). There are currently no checks or warnings.

### CODE REVIEW

**Review by cjmcgill — APPROVED** [review]
Tested tanimoto and morgan similarity and they work!

**Review by hesther — APPROVED** [review]
Thanks! Works (I had tested that this works yesterday anyways).

**Comment by hesther** [comment]
Note: I couldn't get the "embedding" option to run successfully though, but it seems to be a different, unrelated problem, so I think we should still merge this request, and care for the embedding option later on

**Comment by hesther** [comment]
Just tried again - after suggestion from Chas, I produced a new, up-to-date checkpoint file, then the embedding option runs fine. It is not compatible with older checkpoint files though, and in that case throws a rather cryptic error.

**Pull request merged**
