### PR TITLE
move backend to `torch_scatter`

### PR DESCRIPTION
**Pull request by davidegraff**
## Description
This PR moves the backend message-passing code over to using `torch_scatter` from indexing with native `torch`

## Current code
At a high level, message passing over graphs involves a series of `scatter` and `gather` operations. Currently, we achieve this in the `MessagingBlockBase` class like so:
https://github.com/chemprop/chemprop/blob/21446652fdd51362698e8ffdbf35cb8074dbe466/chemprop/v2/models/modules/message_passing/molecule.py#L219-L240

Specifically, on L228, we "scatter" the hidden state of edge to its "source" node (i.e., sending a message $m_{u \to v}$) and then in L229--230 we "gather" the messages incoming to each node (i.e., $m_{u \to v} = \sum_{w \in \mathcal N(u) \setminus v} m_{w \to u}$).

This works, but these same operations have been optimized for CUDA via the [`torch_scatter`](https://github.com/rusty1s/pytorch_scatter/tree/master) package, so we should move our backend model code over to make use of these optimizations.

## Updated code
Starting at the highest level, the newly refactored backend has allowed us to modularize the message scheme, like [so](
https://github.com/davidegraff/chemprop/blob/02c7e7eead28ddae7448575b72e2fd572bb33918/chemprop/v2/nn/message_passing/message_passing.py#L194-L205):
```python
def forward(...):
    H_0 = self.initialize(bmg)


    H = self.tau(H_0)
    for _ in range(1, self.depth):
        if self.undirected:
            H = (H + H[bmg.rev_edge_index]) / 2

        M = self.message(H, bmg)
        H = self.update(M, H_0)

    M = scatter_sum(H, bmg.edge_index[1], 0, dim_size=len(bmg.V))
    return self.finalize(M, bmg.V, V_d)
```

in more detail, this is what message passing looks like [now](https://github.com/davidegraff/chemprop/blob/02c7e7eead28ddae7448575b72e2fd572bb33918/chemprop/v2/nn/message_passing/message_passing.py#L249-L253):
```python
def message(self, H: Tensor, bmg: BatchMolGraph) -> Tensor:
    M_all = scatter_sum(H, bmg.edge_index[1], 0)[bmg.edge_index[0]]
    M_rev = H[bmg.rev_edge_index]

    return M_all - M_rev
```
That is, both the "scatter" and "gather" operations have been subsumed into a single function, `scatter_sum`, from `torch_scatter`. The major benefit of this change is that `scatter_sum` implements both the scatter and gather operations using low-level optimized code as opposed to the high-level torch-based indexing of before!

## Major changes
- broad changes to the overall package organization:
  - MPNN components have been moved to the top level `chemprop.v2.nn` submodule
  - the `chemprop.v2.models` submodule has been cleaned up as a result
  - `schedulers` has been moved to the top level (IMO it shouldn't go inside `nn` in analogy to the organization of `torch`--maybe `chemprop.v2.optim`?)
  - batch collation functions/classes have been moved into a separate submodule: `chemprop.v2.data.collate`
  - some featurization packages have been moved around `molecule` → `molgraph`, `featurizers` → `molecule`, and `protos` is no more (each submodule now owns its respective `Protocol`.
- implementations of `MessagePassingBase` are now defined by the following functions:
  - `initialize`: set up the message passing scheme
  - `message`: calculate the aggregated message vector for each edge in the graph
  - `update` (has default implementation)
  - `finalize` (has default implementation)
- changes to the `{Batch}MolGraph` to make it amenable to new `torch_scatter` code:
  - `a2a`, `a2b`, `b2a`, and `b2revb` are no more. They have been replaced entirely by `edge_index` and `rev_edge_index`. `edge_index` is a tensor of shape `2 x n_edges` (where `n_edges = 2 * n_bonds`) where an entry `edge_index[0][i]` indicates the source node of an edge and `edge_index[1][i]` the destination. This is the sparse COO format of a dense adjacency matrix. `rev_edge_index` is a vector of length `n_edges` that maps from an index to the index of the source of the reverse edge. Yes, that's a mouthful, but it's the same principle as the previous `b2revb` attribute.
  - What has also changed is that edge featurization no longer concatenates source atom features. This is handled during message passing initialization and avoids duplicate data storage (and thus faster CPU<->GPU data transfer)

## What you need to change
Nothing!*

*<sup>Provided you were not directly interacting with the previous message passing or molgraph internals </sup>

That is to say, these changes should be entirely internal to the codebase and will only affect unit tests. Data is still prepared, loaded, and passed into the model with the **exact** same code as before! 

## Why you should care
Briefly, **this new PR makes Chemprop 100% faster.** Moving the backend over to `torch_scatter` has massively improved the bottleneck speed. See below:
| version | batches/sec (`batch_size=50`) | CPUs | GPUs |
| --- | --- | --- | --- |
| v1 | 50 | 8 | 1 |
| v2 (current) | 50 | 4 | 1 |
| v2 (torch_scatter) | 100 | 8 | 1 |

That is to say, with the first version of the code, we needed 8 CPUs and 1 GPU to hit our upper limit of 50 batches/s. With the improved featurization scheme of v2, we could hit our bottleneck using only 4 CPUs. We're much faster in this current PR at 4 CPUs + 1 GPU (~65 batches/s) **and** we are back to being CPU limited at 4 CPUs. Pushing back up to 8 CPUs, we now hit a GPU bottleneck of 100 batches/s.

## Looking forward
One thing this new modularization scheme allows us to is go even one step further! Message-passing schemes are not monoliths like we've coded them up currently. Rather, they're directly composed of three functions: (1) message function $M$, (2) permutation-invariant aggregation scheme $A$, and (3) update function function $U$. In a future version of chemprop (maybe 3.0???), we should further modularize the message passing class to be directly composed of these functions as opposed to the inheritance-based model we're currently using.
If appropriate, please tag them here and include a quick summary

## Checklist
- [x] linted with flake8?
- [x] new integration tests to check for overfitting capability!

## PR Stack
- #514
- #470 <-- HERE
- #552
- #536
- #537

### CODE REVIEW

**Comment by KnathanM** [comment]
I see you bulleted three sets of major changes. I wonder if it would be possible to split this PR into multiple pull requests. Maybe one for the package organization changes and another for the changes involving `torch_scatter`. I'm newer to git and have a harder time reviewing large PRs. 

As we've talked about off GitHub, this PR will be further reviewed after the initial v2 beta is ready.

**Comment by kevingreenman** [comment]
Note: should be merged after #480

**Comment by kevingreenman** [comment]
@davidegraff can you resolve the conflicts before I review?

**Comment by davidegraff** [comment]
Should be all resolved now with all unit tests passing again with the exception of:
- those relying on `regression.csv`. I'm not sure where this file is supposed to be.
- CGR featurization unit tests. I don't really understand how the test was written so it's hard to amend it.

**Comment by kevingreenman** [comment]
I'm guessing `regression.csv` is referring to [this](https://github.com/chemprop/chemprop/blob/v2/dev/tests/data/regression.csv)? Does this just need to be moved from `tests/data/` to `chemprop/v2/tests/data/`?

**Comment by kevingreenman** [comment]
@xiaoruiDong are you able to help us understand why the CGR unit test is failing?

**Comment by xiaoruiDong** [comment]
> @xiaoruiDong are you able to help us understand why the CGR unit test is failing?
will take a look.

**Comment by xiaoruiDong** [comment]
> @xiaoruiDong are you able to help us understand why the CGR unit test is failing?

I managed to adapt the unit tests for CGR to the changes introduced in this PR. To avoid directly pushing to David's branch, I pushed the changes to my fork; see commit 006bd61 and f62ecdc. The previous tries to improve the readability a little bit, and the latter is the actual change. Please feel free to cherry-pick or merge them in.

**Comment by xiaoruiDong** [comment]
@kevingreenman The changes to CGR unit tests are pushed to David's branch in 3 commits. I included a summary of actions in each commit's message to provide hints for reviewing.

**Comment by davidegraff** [comment]
all the unit tests are passing now with a fix in `v1_to_v2.py`

**Comment by davidegraff** [comment]
oh h*ck yeah. It's passing now

**Review by kevingreenman — APPROVED** [review]

**Pull request merged**
