### PR TITLE
Update featurization.py

### PR DESCRIPTION
**Pull request by hl2500**
Is it mapping between atoms?

### CODE REVIEW

**Comment by hesther** [comment]
Yes, that is correct, thanks for catching that (and sorry for the late reply)! Would you be able to pull the changes that were committed since you forked off, rebase and force push to this branch? Also, let me know if you need help with that. Since this is your private repo branch, I unfortunately cannot do it for you. Thanks!

**Comment by hl2500** [comment]
> Yes, that is correct, thanks for catching that (and sorry for the late reply)! Would you be able to pull the changes that were committed since you forked off, rebase and force push to this branch? Also, let me know if you need help with that. Since this is your private repo branch, I unfortunately cannot do it for you. Thanks!

Thank you for the reply! I may not be able to pull the change. It says at least 1 approving review is required by reviewers with write access. Is there another way to do this? Thank you so much!

**Comment by hesther** [comment]
I guess you could also just fork the newest version, change the one line, and submit a new pull request. Sorry for the extra work.

You should only need an approving review to merge, but not to pull changes, or push to your own fork, so I am not 100% what the problem is.

**Comment by hesther** [comment]
Oh, and I have just realised that you are trying to push to master - could you instead make a branch? Thank you!

**Comment by hesther** [comment]
Also, I think we have some misunderstanding on phrases (git can be confusing in the beginning, no worries :) ):
- "Pull" means that you would incorporate the changes on Chemprop's master branch that have happened since you committed this PR. These are not your changes, but the changes others made in the mean time. The respective command would be "git pull".
- Rebase would mean that you put your changes on the top of all other changes ("git rebase")
- "Push" means that you would commit and upload your own changes. The respective command would be "git push". Since you said that you weren't able to "pull changes", I think there was a misunderstanding, sorry! I am asking that you would update your own fork (hl2500:master) where you have rights to write, but preferably create a branch there. I will do all the changes necessary to chemprop, once I heard back from you, since you don't have write access in the chemprop repo (and I need to approve the changes).

**Comment by hl2500** [comment]
> Also, I think we have some misunderstanding on phrases (git can be confusing in the beginning, no worries :) ):
> 
> * "Pull" means that you would incorporate the changes on Chemprop's master branch that have happened since you committed this PR. These are not your changes, but the changes others made in the mean time. The respective command would be "git pull".
> * Rebase would mean that you put your changes on the top of all other changes ("git rebase")
> * "Push" means that you would commit and upload your own changes. The respective command would be "git push". Since you said that you weren't able to "pull changes", I think there was a misunderstanding, sorry! I am asking that you would update your own fork (hl2500:master) where you have rights to write, but preferably create a branch there. I will do all the changes necessary to chemprop, once I heard back from you, since you don't have write access in the chemprop repo (and I need to approve the changes).

Thank you so much for the information! I have synced my fork from upstream and created a brach, featurization_update.

**Review by hesther — APPROVED** [review]

**Comment by hesther** [comment]
Thanks! Since you have now merged in the upstream changes, I will go ahead and merge this request once the tests are finished (so nothing more to do). Thank you very much for contributing to Chemprop, and reading the docstrings carefully!

FYI: I unfortunately could not make use of the nice branch you now made, because changing the source branch of a pull request is not possible (you would have to submit a new one, but since this change is so minor, I don't want to cause you any more extra work than I already did. The upstream changes were the most important anyways). For future reference, this [workflow here](https://gist.github.com/Chaser324/ce0505fbed06b947d962) describes how to fork a repo, keep it aligned with all the upstream changes, create a branch, and then create a merge request from that branch (that would have made it a bit easier for me to merge). But that is really just for future reference; for this PR, I can just merge it now!

**Pull request merged**
