### PR TITLE
Bug: Move `task_weights` to 'device' for MCC metrics

### PR DESCRIPTION
**Pull request by YoochanMyung**
## Description
When running on a GPU, using MCC metrics such as `BinaryMCCMetric()` results in the following error: `RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!`

## Example / Current workflow
```
    188     preds = preds.sigmoid()
    190 L = self._calc_unreduced_loss(preds, targets.long(), mask, weights, *args)
--> 191 L = L * self.task_weights
    193 return L.mean()

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

## Bugfix / Desired workflow
Retrieve the device information from `preds` and move the tensors to the device using the `to` method.

## Checklist
- [ ] linted with flake8?
- [ ] (if appropriate) unit tests added?

### CODE REVIEW

**Comment by JacksonBurns** [comment]
@KnathanM why is lightning not moving this for us?

**Review by KnathanM — APPROVED** [review]
I assume this won't really affect timing and that we don't need to move the task_weights back off of the GPU when we are done.

**Comment by shihchengli** [comment]
@YoochanMyung Thanks for the PR. I expect this will also happen at L75. Could you replace `self.task_weights.view(1, -1)` with `self.task_weights.to(preds.device).view(1, -1)`?

**Comment by KnathanM** [comment]
It isn't a problem at L75 because loss functions are properly registered as submodules. `nn.Metric` overrides the forward method for most of the metrics that also inherit from a loss function, but `BinaryMCCLoss` and `MulticlassMCCLoss` have their own forward methods that use `task_weights` that override the forward in `nn.Metric`. That's a bit confusing so let me know if I should clarify.

**Comment by shihchengli** [comment]
@KnathanM Good catch! Thanks for the explanation.

**Review by shihchengli — APPROVED** [review]

**Pull request merged**
