### PR TITLE
 V2: Add more example notebooks

### PR DESCRIPTION
**Pull request by kevingreenman**
Continued from #676, which was closed when I moved the branch from the chemprop organization to my personal fork. Please see discussion and unresolved action items there.

### CODE REVIEW

**Comment by kevingreenman** [comment]
per the checklist in #556 / #676, we should also consider adding notebooks for the following, many of which were requested by MLPDS members:

- [ ] active learning
- [ ] attribution (#698)
- [ ] transfer learning
- [ ] custom loss functions
- [ ] HPO
- [ ] custom featurizers (@hwpang)

**Comment by kevingreenman** [comment]
> * [ ]  custom featurizers and interoperability (@hwpang, [[TODO]: Add example notebook(s) for interoperability between chemprop and other libraries #804](https://github.com/chemprop/chemprop/issues/804))

@hwpang when we add a new example notebook for custom featurizers, we should be sure we have a good example of how to use the rdkit features that were easy to do in the v1 CLI, as requested in #843 and #849

**Comment by KnathanM** [comment]
My PR #834 added a very small example of writing custom loss functions. Is that enough to check off that box, or do we want a longer worked example?

**Comment by kevingreenman** [comment]
> My PR #834 added a very small example of writing custom loss functions. Is that enough to check off that box, or do we want a longer worked example?

I think maybe a little more detail than what we have so far in #834, but that's a good start

**Comment by JacksonBurns** [comment]
Commenting that the linked issue removed just above my comment was un-linked because this PR will no longer attempt to run the notebooks on Colab/Binder. See that issue for why.

**Pull request closed without merging**
