### PR TITLE
Dummy PR to test github actions

### PR DESCRIPTION
**Pull request by cjmcgill**
It looks like mac-3.8 testing is hanging in the pytest on github actions. I am submitting this dummy PR to test how it behaves. There are no functional changes in this PR and the last PR to merge to master passed testing. So if this PR hangs on testing, then this is an indication that something has changed apart from the code (testing system, dependencies, etc) to cause the problem.

### CODE REVIEW

**Comment by hesther** [comment]
This problems seems to be weirdly specific, occurring three times in a row with macOS python 3.8 ... I often run chemprop on macOS, never had a problem. I now restarted the tests, in the past that has sometimes solved the problem (although it worries me that it happened in three different PRs)

**Comment by hesther** [comment]
Mmh restarting doesn't work...

**Comment by mliu49** [comment]
Could this be related to #115, or rather multiprocessing behavior on MacOS with Python 3.8 in general?

Here's the tail of the logs. Nothing particularly insightful...
```
2021-07-21T04:48:07.8186360Z ============================= test session starts ==============================
2021-07-21T04:48:07.8188780Z platform darwin -- Python 3.8.10, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
2021-07-21T04:48:07.8190100Z rootdir: /Users/runner/work/chemprop/chemprop
2021-07-21T04:48:07.8191070Z collected 25 items
2021-07-21T04:48:07.8191750Z 
2021-07-21T10:42:08.6439280Z ##[error]The operation was canceled.
2021-07-21T10:42:09.2435620Z Post job cleanup.
2021-07-21T10:42:14.9872000Z [command]/usr/local/bin/git version
2021-07-21T10:42:15.4423400Z git version 2.32.0
2021-07-21T10:42:15.5039410Z [command]/usr/local/bin/git config --local --name-only --get-regexp core\.sshCommand
2021-07-21T10:42:15.5612430Z [command]/usr/local/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
2021-07-21T10:42:16.2954000Z [command]/usr/local/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2021-07-21T10:42:16.3064300Z http.https://github.com/.extraheader
2021-07-21T10:42:16.3125570Z [command]/usr/local/bin/git config --local --unset-all http.https://github.com/.extraheader
2021-07-21T10:42:16.3456850Z [command]/usr/local/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
2021-07-21T10:42:16.7308170Z Cleaning up orphan processes
2021-07-21T10:42:17.0903930Z Terminate orphan process: pid (2125) (python3.8)
2021-07-21T10:42:17.1224630Z Terminate orphan process: pid (2116) (python3.8)
```

**Comment by cjmcgill** [comment]
The most recent PR with a successful test was #182 which more recent than the #115 issue.

**Pull request closed without merging**
