### PR TITLE
Adding function to be able add Hydrogens to the rdkit mol

### PR DESCRIPTION
**Pull request by JurgisR**
Simple PR to add the functionality of allowing the user to specify if they want to have the smiles molecules be parametrized with or without Hydrogens.

### CODE REVIEW

**Comment by hesther** [comment]
Thanks for this PR! The changes mostly look good to me.

You would also need to make changes to chemprop/args.py to add the command-line option to add hydrogens (most of our users use the command-line to train models). I also commented on one piece of the code (update a docstring)

**Comment by hesther** [comment]
It also seems like you missed to update a few make_mols calls (see LGTM output)

**Comment by JurgisR** [comment]
Updated! Thanks for the input!

**Comment by hesther** [comment]
Just ran some tests, I think the argument is not initialised correctly. You will need to make changes to `chemprop/train/cross_validate.py`, `chemprop/train/make_predictions.py` and `chemprop/train/molecule_fingerprint.py` similar to the line `set_explicit_h(args.explicit_h)` but for adding hs (and add the respective imports)

**Review by hesther — APPROVED** [review]

**Comment by hesther** [comment]
Looks good to me! @JurgisR would you mind squashing your three commits into one and force-pushing to clean up the commit history? Thanks!

**Comment by cjmcgill** [comment]
Sorry, late to the party here. A clarifying question. Is this meant to be overridden by explicit_h? Because it looks like activating it in rdkit.py is lower in the elif order.

**Comment by hesther** [comment]
The options adds additional hydrogens, so we need both options separately. Eg if you read in atom mapped smiles, say [H:1][C:2](=[O:3])[H:4], will turn into [C:2](=[O:3]) without explicit_h and then into [H][C:2](=[O:3])[H] with adding_h… so they cannot override each other. There might also be use cases where only some hydrogens are specified and mapped, so running both options at the same time might make sense in some edge cases

**Comment by cjmcgill** [comment]
The atom mapping is an important case that I forgot about (especially important for reactions of course). So we want these to operate separately, but that’s not how it’s set up in rdkit.py. If you have both keep_h and add_h, it only carries out keep_h because add_h is in a dependent elif block. What we want is a separate if block for add_h that comes after the if/else block for keep_h.

**Comment by hesther** [comment]
Oh, you are right, let me fix that

**Comment by hesther** [comment]
@Chas, can you look at #227

**Pull request merged**
