### PR TITLE
Enable CPU prediction for GPU-trained models

### PR DESCRIPTION
**Pull request by snaeppi**
## Description

Adds a check of accelerator argument to the `load_model` utility. If the accelerator is "cpu", the model is loaded to the CPU by passing `map_location=torch.device("cpu")` to `torch.load`.

## Example / Current workflow

Attempting to use a model trained on GPU for prediction in a CPU-only environment ends in a RuntimeError.

## Bugfix / Desired workflow

Train with GPU:
```
chemprop train --accelerator gpu --task-type regression --data-path somedata.csv
```
Predict with CPU only:
```
CUDA_VISIBLE_DEVICES=-1 chemprop predict --accelerator cpu --devices 1 -n 1 --model-paths chemprop_training/somedata -i predict_something.csv -o results_something.csv
```

## Questions

Is the current scope of this fix (enabling CPU prediction) sufficient, or should it be expanded to handle other device mismatches (e.g., TPU to CUDA)?

## Relevant issues

[#949](https://github.com/chemprop/chemprop/issues/949)

## Checklist
- [ ] linted with flake8?
- [ ] (if appropriate) unit tests added?

### CODE REVIEW

**Review by KnathanM — COMMENTED** [review]
I agree with having `load_model` handle making the `map_location`. My first thought was that the CLI is like a user, so any user tasks (like selecting which device to send the tensors to) should be handled within the CLI and not in `load_model` which resides outside the CLI. But then I see that `load_model` is only used within the CLI and in any case, acts as a convenience wrapper for `.load_from_file` so it is appropriate to have it handle torch.device as a convenience for the user. 

As to whether it should handle more than just taking a gpu model to a cpu, I agree that this is the most common use case. If a user has another use case (e.g tpus, etc.) this feels more advanced and I don't think we need to support this in the CLI.

If `load_model` only handles gpu -> cpu, then I suggest changing `accelerator: str` to something like `cpu: bool` which matches the style of `multicomponent: bool`. Then instead of `args.accelerator`, we could use `args.accelerator == "cpu"`. I think this avoids the confusion of a user passing `accelerator = "gpu"` and it not moving the model to the GPU.

**Comment by shihchengli** [comment]
I think we may not need to manually move the model to the correct device, as the PyTorch Lightning Trainer should handle the device placement for us. If that is correct, we can always load all tensors onto the CPU via `torch.load(path, map_location=lambda storage, loc: storage)` in the `load_model` function.

**Comment by snaeppi** [comment]
Thank you for your feedback. 

The error I mentioned in the issue and in this PR occurs when `torch.load` is called before the model is passed on to the PyTorch Lightning Trainer. Here is the full traceback for your convenience:
```
Traceback (most recent call last):
  File "/envs/chemprop-2/bin/chemprop", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/chemprop-2/chemprop/cli/main.py", line 80, in main
    func(args)
  File "/chemprop-2/chemprop/cli/predict.py", line 35, in func
    main(args)
  File "/chemprop-2/chemprop/cli/predict.py", line 343, in main
    make_prediction_for_models(args, model_paths, multicomponent, output_path=args.output)
  File "/chemprop-2/chemprop/cli/predict.py", line 192, in make_prediction_for_models
    model = load_model(model_paths[0], multicomponent)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/chemprop-2/chemprop/models/utils.py", line 17, in load_model
    model = MPNN.load_from_file(path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/chemprop-2/chemprop/models/model.py", line 254, in load_from_file
    d = torch.load(model_path, map_location=map_location)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/envs/chemprop-2/lib/python3.11/site-packages/torch/serialization.py", line 1025, in load
    return _load(opened_zipfile),
           ^^^^^^^^^^^^^^^^^^^^^
  File "/envs/chemprop-2/lib/python3.11/site-packages/torch/serialization.py", line 1446, in _load
    result = unpickler.load()
             ^^^^^^^^^^^^^^^^
  File "/envs/chemprop-2/lib/python3.11/site-packages/torch/serialization.py", line 1416, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/envs/chemprop-2/lib/python3.11/site-packages/torch/serialization.py", line 1390, in load_tensor
    wrap_storage=restore_location(storage, location),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/envs/chemprop-2/lib/python3.11/site-packages/torch/serialization.py", line 390, in default_restore_location
    result = fn(storage, location)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/envs/chemprop-2/lib/python3.11/site-packages/torch/serialization.py", line 265, in _cuda_deserialize
    device = validate_cuda_device(location)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/envs/chemprop-2/lib/python3.11/site-packages/torch/serialization.py", line 249, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```
I agree with @shihchengli's suggestion to use `map_location=lambda storage, loc: storage` and allow PyTorch Lightning to handle the device placement later.

**Comment by shihchengli** [comment]
@snaeppi thanks for opening this PR and contributing the code. You can click the "Ready for review" button if you think this is ready.

**Review by shihchengli — APPROVED** [review]

**Pull request merged**
