### PR TITLE
update authors in LICENSE and setup files for v1

### PR DESCRIPTION
**Pull request by kevingreenman**
I realized a couple things after merging #532:
* there are also authors lists in the `setup.py` and `setup.cfg` files that should probably also be updated to match the new list in the `LICENSE.txt`
* we left out a couple people in #532: Lior Hirschfeld and Yanfei Guan (who are both relatively high on the [contributors list](https://github.com/chemprop/chemprop/graphs/contributors)), and Allison Tam (who does not show up under GitHub contributions, but was listed in the `setup.py` and `setup.cfg` files)

Note that these new author lists do not include several people who have made significant contributions to the v2 code. They will be added in a future PR related to #489

### CODE REVIEW

**Comment by cjmcgill** [comment]
Good catch on both counts.

**Review by JacksonBurns — COMMENTED** [review]
In the spirit of DRY, might we do this:
 - prefix the list of copyright holders in LICENSE.txt with "The Chemprop Development Team"
 - change the seutp.cfg and setup.py to be attributed to the chemprop development team instead (and perhaps add "see LICENSE.txt").

This would prevent us having to maintain the same list in three places.

**Comment by cjmcgill** [comment]
I agree that we'd want to avoid duplicative updates in multiple places. One of these setup files gets updated by bumpversion right? Could we set up bumpversion to distribute the authorlist to the license file as well?

**Comment by JacksonBurns** [comment]
I just remembered - I'm pretty sure that setup.cfg just provides default values for setup.py, so we might not need to provide author= in setup.py at all. This would need to be checked though, I'm just guessing from memory.

> I agree that we'd want to avoid duplicative updates in multiple places. One of these setup files gets updated by bumpversion right? Could we set up bumpversion to distribute the authorlist to the license file as well?

I'm not sure if bumpversion can do that (just based on a look at their README) by default, though we might be able to hack its regex searcher a bit to find and replace the author list. I don't think this is worth the effort.

**Comment by cjmcgill** [comment]
Yeah modifying bumpversion is not worth it. Better to do your suggestion listing The Chemprop Development Team (see license) or similar

**Comment by kevingreenman** [comment]
@JacksonBurns @cjmcgill good point, I've made the suggested change

**Review by JacksonBurns — APPROVED** [review]
👍 LGTM

**Pull request merged**
