### PR TITLE
Fix bug with extra atom and bond feature scaling

### PR DESCRIPTION
**Pull request by yunsiechung**
This PR fixes the bug addressed in this issue #213.

Bug description:
If both extra atom and bond features are used and scaling is enabled, the same scaler object is used to scale both extra atom and bond features.

Solution:
This commit fixes it by removing the existing atom descriptor scaler before scaling the extra bond features.

### CODE REVIEW

**Comment by yunsiechung** [comment]
@cjmcgill I'm not sure why the tests/build fails at dependency installation.

**Comment by yunsiechung** [comment]
I realized that the same bug occurs if extra molecular features and atom features are used. So I made a change and made a force push.

**Comment by hesther** [comment]
Max and I are still discussing on how to best fix the pip errors (we seem to have found a better solution, see current PR #216). Feel free to remove previous commits and include the new pip bugfix (but maybe wait until Max approves of the new solution).

**Comment by hesther** [comment]
Can someone give this a positive review? :)

**Pull request merged**
