### PR TITLE
[v2 Feature] Implement Shapley value analysis 

### PR DESCRIPTION
**Pull request by oscarwumit**
## Description
This PR aims to implement Shapley value analysis for chemprop v2 models as part of the effort to improve model interpretability as requested by MLPDS members and other users.  

v2 codebase has been updated with the ability to perform needed operations for shap analysis. A notebook is provided to demonstrate how users can compute shap values to explain: (1) importance of specific atom and bond features produced by featurizers, and (2) importance of specific atom or bond. 

Currently, explanation for extra atom/bond/mol features is not supported because there are still open PRs related to them. We can add support for them in a future PR.  

## Checklist
- [ ] linted with flake8?
- [ ] (if appropriate) unit tests added?

### CODE REVIEW

**Comment by davidegraff** [comment]
The model you've taken for including/excluding individual one-hot features in the `MultiHot*Featurizer` implementations is inappropriate. See my comment in #921 for more. Given that this is PR is an extension notebook and not a core library feature, I don't see a reason modify core library code to accommodate it.

**Comment by davidegraff** [comment]
I would encourage you to close this PR, and open up a corresponding issue so we can discuss what, if any, is the correct route to take for this notebook.

**Comment by shihchengli** [comment]
In the notebook, the prediction strings are repeated multiple times, making the file too large. You can try turning off `enable_progress_bar` (it might still print out the devices you are using, so it might not work) or set the logger to False.

> GPU available: False, used: False
> TPU available: False, using: 0 TPU cores
> HPU available: False, using: 0 HPUs
> Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 528.58it/s]

**Comment by shihchengli** [comment]
I'm thinking that this implementation might just be included in a notebook. For example, you can write the atom, bond, and molecule featurizers to inherit from the ones we have in our main codebase, so it can still keep the main library concise.

**Comment by oscarwumit** [comment]
Thanks for the comment and I agree we should have a discussion in the developer meeting. For now, I will keep this PR open for the following reasons:

1. Although I agree that in general we want to keep the core library light, but interpretability is a feature that MLPDS members wanted as they specifically mentioned about it during the last meeting. Also in v1, we had`interpret.py` for a different algorithm that some are trying to make it work for v2. Therefore, I would argue that interpretability is a core feature and it is reasonable to experiment with ways to update the core library functions to enable interpretability analysis.

2. I agree that we should look into how to best implementing SHAP, v1 monte-carlo tree search, or other highly desired interpretability features. For this PR specifically, the current changes do not alter any default behavior of the `MultiHot*Featurizer`. The changes are primarily adding optional flags that can control the behavior of `MultiHot*Featurizer`, which I think is a reasonable expansion and we already have examples of doing this:
https://github.com/chemprop/chemprop/blob/99eef8b7192ee026f5648528d3a7642f428f0aec/chemprop/featurizers/atom.py#L113-L123
This method in the `MultiHotAtomFeaturizer` essentially provides a different encoding. If we are okay with this, then what prohibits us from supporting another similar function like:
https://github.com/chemprop/chemprop/blob/8e988a437304c470ea218e5fa39181cdade8c42f/chemprop/featurizers/atom.py#L136-L138
That said, I am open to suggestions for a better implementation. For example, if we do not want to introduce another optional argument to the class, I can do something else like having a method for it. 

3. Regarding the insightful discussion in https://github.com/chemprop/chemprop/issues/921, I think the mentality in this PR does not conflict with our discussions there. Because in that issue, we seem to agree that the behavior of featurization should in general be controlled at lower level functions such as  `MultiHot*Featurizer` but not get quietly overwritten at some higher-level scripts, for this can introduce unexpected behavior and potential bugs. This PR expanded  `MultiHot*Featurizer` so that now it can produce an masked output as an option, and this change is done with similar thinking we have in that open issue. If we decide to not touch the  `MultiHot*Featurizer` at all, I think the code will actually become more complex if we want to implement something like Shap because now we need to control the encoding at higher-levels, which can introduce bugs. 

With all this, I think we should have a discussion and I am open to suggestions. Thank you.

**Comment by davidegraff** [comment]
> Thanks for the comment and I agree we should have a discussion in the developer meeting. For now, I will keep this PR open for the following reasons:
> 
> 1. Although I agree that in general we want to keep the core library light, but interpretability is a feature that MLPDS members wanted as they specifically mentioned about it during the last meeting. Also in v1, we had`interpret.py` for a different algorithm that some are trying to make it work for v2. Therefore, I would argue that interpretability is a core feature and it is reasonable to experiment with ways to update the core library functions to enable interpretability analysis.

The whole premise of v2 was to trim down the library to make it more readable and maintainable while not precluding extensions like this. Every time someone argues "we had this feature in v1, so we should have it in v2" it fails to appreciate the costs to readability and maintainability that feature bloat incurs. I refer you to previous discussions on the `interpret.py` script from v1, which approximately no one on the dev team understands. It's easy to say: "Well this is just SHAP, a fairly well understood technique," but doing so (1) signs a contract with our user base for future support and (2) places the onus on us to accommodate such a feature within our library, which again, may not be straightfoward.

> 2. I agree that we should look into how to best implementing SHAP, v1 monte-carlo tree search, or other highly desired interpretability features. For this PR specifically, the current changes do not alter any default behavior of the `MultiHot*Featurizer`. The changes are primarily adding optional flags and methods that can control the behavior of `MultiHot*Featurizer`, which I think is a reasonable expansion and we already have examples of doing this:
>    https://github.com/chemprop/chemprop/blob/99eef8b7192ee026f5648528d3a7642f428f0aec/chemprop/featurizers/atom.py#L113-L123
>    
>    This method in the `MultiHotAtomFeaturizer` essentially provides a different encoding. If we are okay with this, then what prohibits us from supporting another similar function like:
>    https://github.com/chemprop/chemprop/blob/8e988a437304c470ea218e5fa39181cdade8c42f/chemprop/featurizers/atom.py#L136-L138

I would argue that your first example supports my point rather than yours: this method is not entirely clear why it exists in the first place, and the only reason for its existence is to support CGR featurization, a core feature in v1. At the original time of writing, I was undecided between adding an additional `SupportsNumOnly(Protocol)` (or something similar) to delineate what sort of atom featurizer a CGR could accept. The current object model is insufficient, but at least it works.

>    That said, I am open to suggestions for a better implementation. For example, if we do not want to introduce another optional argument to the class, I can do something else like having a method for it.
> 3. Regarding the insightful discussion in [[v2 better design?]: Function override can cause unexpected and unclear featurization behavior #921](https://github.com/chemprop/chemprop/issues/921), I think the mentality in this PR does not conflict with our discussions there. Because in that issue, we seem to agree that the behavior of featurization should in general be controlled at lower level functions such as  `MultiHot*Featurizer` but not get quietly overwritten at some higher-level scripts, for this can introduce unexpected behavior and potential bugs.

Again, you keep using the terms "bug" and "overwrite," but these terms are **not accurate** to describe what's happening. I've repeatedly emphasized this. They may be causing difficulty with newer features, but you can't call an inconvenience a bug.

> This PR expanded  `MultiHot*Featurizer` so that now it can produce an masked output as an option, and this change is done with similar thinking we have in that open issue. If we decide to not touch the  `MultiHot*Featurizer` at all, I think the code will actually become more complex if we want to implement something like Shap because now we need to control the encoding at higher-levels, which can introduce bugs.
> 
> With all this, I think we should have a discussion and I am open to suggestions. Thank you.

Adding the `zero_mask()` method is just syntactic sugar. I would argue that between these two choices, neither one is more readable:

```python
af: MultiHotAtomFeaturizer

x = np.zeros(len(af))
x = af.zero_mask
```

But the latter introduces an additional method into the codebase. Again, little changes like these seem "free" and "convenient," but we should strive to keep the codebase (1) readable, (2) efficient, and (3) concise (in that order). If a change does not materially impact any of these (like, e.g., `zero_mask()`), then we should not accept it.

**Comment by JacksonBurns** [comment]
I've not read through this issue, but I am documenting some discussion from an offline meeting:
 - we agreed that this feature would be best presented in a notebook
 - we would also like that notebook to demonstrate how to inherit from and extend Chemprop's classes
 - if that proves to be very difficult, we will circle back to the idea of modifying the base class

**Comment by oscarwumit** [comment]
Thanks. Based on today's offline discussion, I will try to implement the feature in a notebook and update this PR accordingly.

**Comment by oscarwumit** [comment]
Replaced by https://github.com/chemprop/chemprop/pull/938

**Pull request closed without merging**
