### PR TITLE
update readme and docs

### PR DESCRIPTION
**Pull request by hesther**
Added information in the readme and the documentation (as requested) on:

- pretraining
- treatment of missing values in multitask models
- caching

as well as added the description of the reaction mode to the documentation (which was already in the readme).

### CODE REVIEW

**Review by cjmcgill — APPROVED** [review]
These additions look good by me. I don't see anything that needs changing or correction.

**Comment by hesther** [comment]
@cjmcgill I ran some more tests today, and it seems like whether changing the caching default is actually beneficial depends very much on whether one uses a cpu or gpu - should I maybe mention this? (For training on gpus it is better to not cache, and instead use a large amount of workers to create the graphs each epoch)

**Comment by cjmcgill** [comment]
That sounds like extremely useful information

**Comment by hesther** [comment]
I included a note about when changing the caching behavior might be beneficial. I guess this is ready to be merged?

**Pull request merged**
