### PR TITLE
Parallel feature generation

### PR DESCRIPTION
**Pull request by guyrosin**
## Description
Speed up generating features using multiprocessing.

This PR parallelizes the creation of `MoleculeDatapoint`s, which is where features are calculated.

## Example / Current workflow
Outputs should stay the same; generating features should work much faster. 
Any workflow that involves generating features should be affected (such as training a model with specified feature generators and predicting using such a model)
For example:
`chemprop_train --features_generator rdkit_2d_normalized --no_features_scaling --data_path data/tox21.csv --dataset_type classification --save_dir tox21_checkpoints`

## Bugfix / Desired workflow
See above - outputs should not change.

### CODE REVIEW

**Comment by davidegraff** [comment]
Hi @guyrosin, thanks for the PR! this is a nice, straightforward addition to the current codebase. I have a few comments/questions:

* do you have timing samples to provide?
* have you tried batching in the `map` operation? Does it lead to any improvement?
* would it be possible to add CPU specification to the method definition? Currently, it just calls creates a `Pool` with all *visible* CPUs on the machine, but this isn't always the case (e.g., SLURM clusters.) We also might want to allow a user to artificially restrict the amount of resources given to this task by specifying a lower core count in the function call.

**Comment by davidegraff** [comment]
Also, would it be possible to add unit tests for your PR to verify that that parallel feature generation is the same as sequential? Or, at the very least, could you provide some sample runs?

**Comment by oscarwumit** [comment]
What's the status of this PR?

**Comment by davidegraff** [comment]
closing this due to lack of activity

**Pull request closed without merging**
