### PR TITLE
Add example notebook for training and predicting multicomponent regression

### PR DESCRIPTION
**Pull request by hwpang**
## Description
Add an example notebook for training multicomponent MPNN for regression task. Currently blocked by https://github.com/chemprop/chemprop/pull/522 and https://github.com/chemprop/chemprop/pull/521.

### CODE REVIEW

**Comment by JacksonBurns** [comment]
This is actually broken far beyond just split_data. Currently the training script does not seem to have any way to actually handle this? And shouldn't cross validation allow split types other just random? Will need an offline meeting about this.

**Comment by hwpang** [comment]
@JacksonBurns 's comment is meant for https://github.com/chemprop/chemprop/pull/521, not this PR.

**Comment by hwpang** [comment]
I added the notebook to the github workflow for testing. It's currently failing because this PR depends on https://github.com/chemprop/chemprop/pull/522.

**Comment by hwpang** [comment]
I rebased this onto the branch in https://github.com/chemprop/chemprop/pull/522 for the tests to pass. https://github.com/chemprop/chemprop/pull/522 needs to be merged before this.

**Comment by KnathanM** [comment]
Looks good to me. Will approve and merge after #522

**Review by KnathanM — APPROVED** [review]

**Pull request merged**
