### PR TITLE
Fix Circular Import with `isort`

### PR DESCRIPTION
**Pull request by JacksonBurns**
## Description
If you run `isort` on the codebase and then `pytest`, this error comes up:
```
tests/integration/conftest.py:5: in <module>
    from chemprop import models, nn
chemprop/__init__.py:1: in <module>
    from . import conf, data, exceptions, featurizers, models, nn, schedulers, utils
chemprop/conf.py:3: in <module>
    from chemprop.featurizers.molgraph.molecule import SimpleMoleculeMolGraphFeaturizer
chemprop/featurizers/__init__.py:1: in <module>
    from .atom import AtomFeatureMode, MultiHotAtomFeaturizer, get_multi_hot_atom_featurizer
chemprop/featurizers/atom.py:7: in <module>
    from chemprop.featurizers.base import VectorFeaturizer
chemprop/featurizers/base.py:7: in <module>
    from chemprop.data.molgraph import MolGraph
chemprop/data/__init__.py:1: in <module>
    from .collate import BatchMolGraph, TrainingBatch, collate_batch, collate_multicomponent
chemprop/data/collate.py:8: in <module>
    from chemprop.data.datasets import Datum
chemprop/data/datasets.py:12: in <module>
    from chemprop.data.datapoints import MoleculeDatapoint, ReactionDatapoint
chemprop/data/datapoints.py:8: in <module>
    from chemprop.featurizers import Featurizer
E   ImportError: cannot import name 'Featurizer' from partially initialized module 'chemprop.featurizers' (most likely due to a circular import) (/home/jackson/chemprop/chemprop/chemprop/featurizers/__init__.py)
```
As it turns out, we are sensitive to the order of imports in `chemprop/__init__.py`.

## Fix
This PR removes the export causing the problem (`conf.py`) and then applies `isort`. This PR would replace #807, which instead just skips `isort`-ing this line.

Removing this has only one change on the use of Chemprop - now running `from chemprop import *` will not result in `conf` being imported. This isn't something we do anywhere and isn't advisable in general, so I don't think this is a big problem.

I have only run `pytest --collect-only` so far - CI will show if something else went wrong.

This PR (or #807) completes https://github.com/chemprop/chemprop/issues/494

### CODE REVIEW

**Review by hwpang — APPROVED** [review]
LGTM

**Comment by hwpang** [comment]
By the way, were you able to figure out a way to make isort to sort the reexport list?

**Comment by JacksonBurns** [comment]
> By the way, were you able to figure out a way to make isort to sort the reexport list?

No, I ran into the same issues that you had on your PR

**Review by KnathanM — APPROVED** [review]
To me, the need to not include `chemprop/conf.py` in `chemprop/__init__.py` shows its content is misplaced. We could put the `DEFAULT_ATOM_FDIM` and `DEFAULT_BOND_FDIM` directly in `chemprop/nn/message_passing/base.py` (the only place it is used) and then not have this issue with circular imports. 

But this solution works so this solution works for me.

**Pull request merged**
