### PR TITLE
Fix unused parameters issue in DDP

### PR DESCRIPTION
**Pull request by shihchengli**
## Description
Address issue #853. There are two parameters (`message_passing.W_d.weight` and `message_passing.W_d.bias`) not used during training when `d_vd` is 0. The matrix is used when additional atomic descriptors are provided. This learned matrix should only be initiated when additional atomic descriptors are provided.

## Relevant issues
#853 

## Checklist
- [ ] linted with flake8?
- [ ] (if appropriate) unit tests added?

### CODE REVIEW

**Review by JacksonBurns — COMMENTED** [review]
My only small request would be to add a comment above this line saying that `d_vd` is or isn't since we are now relying on it being implicitly false. Thanks for fixing this!

**Review by JacksonBurns — APPROVED** [review]

**Comment by shihchengli** [comment]
@JacksonBurns thank you for reviewing this PR. I've added a new commit to remove `find_unused_parameters` in HPO, as it is not necessary within the changes of this PR.

**Comment by KnathanM** [comment]
Why were the example model files regenerated for this PR? Are model files created in v2.0.0 not compatible with this PR? If so, we will need to include that in the release notes when we release v2.0.1.

**Comment by shihchengli** [comment]
Yes, the message_passing.W_d.weight and message_passing.W_d.bias are not saved in the checkpoint after this change.

**Pull request merged**
